=== giisbertito/tema03/ej1_items.dtd
<!ELEMENT minecraftItems (item+)>
<!ATTLIST minecraftItems lang CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT item (name, type, damage?, description, materiales?, encantamientos?)>

<!ATTLIST item id ID #REQUIRED
               rareza (comÃºn | raro | legendario) #REQUIRED
               crafteable (true | false) #REQUIRED
               encantable (true | false) #REQUIRED>

<!ELEMENT materiales (material+)>
<!ELEMENT material (#PCDATA)>

<!ELEMENT encantamientos (encantamiento+)>
<!ELEMENT encantamiento (#PCDATA)>

=== giisbertito/tema03/ej1_items.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE minecraftItems SYSTEM "ej1_items.dtd">
<minecraftItems lang="es">
    <item id="minecraft_diamond_sword" rarity="raro" crafteable="true" encantable="true">
        <name>Espada de Diamante</name>
        <type>arma</type>
        <damage>7</damage>
        <description>Espada de diamante para atacar a los enemigos</description>
        <materiales>
            <material>Diamante</material>
            <material>Palo</material>
        </materiales>
        <encantamientos>
            <encantamiento>Afilado V</encantamiento>
            <encantamiento>Irrompibilidad II</encantamiento>
        </encantamientos>
    </item>
    <item id="minecraft_button" rarity="común" crafteable="true" encantable="false">
        <name>Botón</name>
        <type>bloque</type>
        <damage>Accionar mecanismos</damage>
        <description>Boton de madera para accionar mecanismos</description>
        <materiales>
            <material>Madera</material>
        </materiales>
    </item>
    <item id="minecraft_lighter" rarity="legendario" crafteable="true" encantable="false">
        <name>Mechero</name>
        <type>herramienta</type>
        <damage>daño progresivo</damage>
        <description>Mechero utilizado para prender objetos</description>
        <materiales>
            <material>Hierro</material>
            <material>Pedernal</material>
        </materiales>
    </item>
</minecraftItems>
